name: Lint
# This workflow is triggered on pull request to the repository.
on: [pull_request]

jobs:
  lint:
    name: Lint
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Comment on new PR
      uses: brown-ccv/alex-recommends@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        profanity_sureness: 2