name: Generate Preview
on: pull_request

jobs:
  generate-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Deploy Preview
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages
          folder: out
          target-folder: preview/preview/preview/${{github.event.number}}

      - name: Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Preview available at https://custom-elements-everywhere.com/preview/preview/preview/${{github.event.number}}/
