name: Test that the site builds

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - run: npm test

      - name: Deploy Preview
        if: ${{github.event_name == 'pull_request'}}
        uses: JamesIves/github-pages-deploy-action@4.2.1
        with:
          branch: gh-pages
          folder: out
          target-folder: preview/preview/preview/${{github.event.number}}
      - name: Comment about preview
        if: ${{github.event_name == 'pull_request'}}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Preview this PR: https://custom-elements-everywhere.com/preview/preview/preview/${{github.event.number}}/
